results_topic: "/dialogflow_client/results"
requests_topic: "/dialogflow_client/requests"
project_id: "personal-reminder-qreb"
play_audio: true
use_audio_server: false
server_name: "127.0.0.1"
port: 4444
debug: false

text_topic: "/dialogflow_client/requests/string_msg"
